### PR TITLE
OWA-98: Cohort Builder for Condition List

### PR DESCRIPTION
**Pull request by haripriya999**
# OWA-98: Cohort Builder for Condition List

## Description of what I changed
Write a RefApp ConditionList report in  CohortBuilder to export data

## Issue I worked on

see https://issues.openmrs.org/browse/OWA-98

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
Did you see my comments on the ticket?

**Comment by haripriya999** [comment]
> Did you see my comments on the ticket?

@dkayiwa  I updated the PR

**Comment by haripriya999** [comment]
@dkayiwa I updated the PR

**Comment by dkayiwa** [comment]
The ticket status shows that you are still doing more work on it.

**Comment by haripriya999** [comment]
> The ticket status shows that you are still doing more work on it.

@dkayiwa  I updated the status

**Comment by dkayiwa** [comment]
Can you point me to where you are passing the selected dates to the server side request?

**Comment by dkayiwa** [comment]
I have added a condition to a patient, went to the cohort builder and searched, got the no results found message. Even your screenshots show 0 results.

**Comment by haripriya999** [comment]
@dkayiwa Thank you for your insight on this, I am trying to explore this problem. I see calls are being made to 'reportingrest/adhocquery?v=full' to fetch data,  as seen here: https://github.com/openmrs/openmrs-owa-cohortbuilder/blob/master/app/js/components/tabs/tabsComponent.jsx#L47-L60. I think there might be some issue over here:https://github.com/openmrs/openmrs-module-reportingrest/blob/master/omod/src/main/java/org/openmrs/module/reportingrest/web/resource/AdHocQueryResource.java , I'm trying to communicate with Darius who wrote this code.

**Comment by haripriya999** [comment]
> I have added a condition to a patient, went to the cohort builder and searched, got the no results found message. Even your screenshots show 0 results.

@dkayiwa  I see this to be happening in the concept tab as well. Could you suggest on, what could be the possible solution for this? Thank you

**Comment by dkayiwa** [comment]
Did you try to investigate?

**Comment by haripriya999** [comment]
> Did you try to investigate?

@dkayiwa , I'm on it. https://github.com/openmrs/openmrs-owa-cohortbuilder/pull/182#issuecomment-520931240  . I'm having a bit difficult time understanding how  this:https://github.com/openmrs/openmrs-module-reportingrest/blob/master/omod/src/main/java/org/openmrs/module/reportingrest/web/resource/AdHocQueryResource.java  code is fetching the required results. I messaged Darius but didn't receive any response yet.

**Comment by haripriya999** [comment]
@dkayiwa On digging into the code, I discovered we have these evaluators: https://github.com/openmrs/openmrs-module-reporting/tree/master/api/src/main/java/org/openmrs/module/reporting/cohort/definition/evaluator in reporting module. I don't see an evaluator for concepts. Should I add one for concepts? How should this be working?

**Comment by mozzy11** [comment]
@haripriya999  the above query ,literally filters and returns patients based on a given coded_obs value.
However even that cant work. i created a [ticket here](https://issues.openmrs.org/browse/REPORT-855) ,made a PR ,,and tried to give an explanation in the comments why, patients can not be filtered based on the coded_obs value.
 in brief 
* The corhort OWA sends a wrong Request payLoad 
* A "SetComparator" parameter was not added to the  CodedObsCohortDefinition , yet its a key parameter that is used to filter the patients in the CodedObsCohortDefinitionEvaluator

See above ticket for more description of the cause of the bug

**Comment by mozzy11** [comment]
However , The above query we are addresing above , returns patients with a given Coded_obs Value. 
Now what you need is a query that returns a list of patients with a given condition. 
So i created this [Another ticket here](https://issues.openmrs.org/browse/REPORT-856) , and am working on it , to create a ConditonCohortDefinition , that will return a list of patients with a given conditon and considering other parameters like date range

**Comment by mozzy11** [comment]
@haripriya999  and @dkayiwa  Created this PR here https://github.com/openmrs/openmrs-module-reporting/pull/184/files
for this ticket https://issues.openmrs.org/browse/REPORT-856

**Comment by dkayiwa** [comment]
Thanks @mozzy11 😊

**Comment by dkayiwa** [comment]
@haripriya999 are you still working on this?

**Pull request closed without merging**
