### PR TITLE
CB-172: Reset form when user clicks ‘Search’ - Saved

### PR DESCRIPTION
**Pull request by joel-ace**
# JIRA TICKET NAME:
[Reset form when user clicks ‘Search’ - Saved](https://issues.openmrs.org/browse/CB-172)

## SUMMARY:
This PR ensures that on the "Saved" tab, the form is reset when the Search button is clicked

### CODE REVIEW

**Review by andela-dbamidele — COMMENTED** [review]
Great Job! 👍

**Review by kwahalf — COMMENTED** [review]
looks good

**Comment by cnagadya** [comment]
Good work @joel-ace . Since you are already working on this file, take a look at [this article](https://improvingsoftware.com/2011/06/27/5-best-practices-for-commenting-your-code/) that was shared with the OpenMRs devs in September regarding code comments

**Comment by joel-ace** [comment]
Thank's @cnagadya I've read that article before. I didn't take out those comments for two reasons:
- The comments are quite descriptive and help with a quick start. Considering that there's a greater possibility of devs that are new to JS working on the project, I don't think it's a bad idea having them there. Also, the comment to code ratio on this file is really low
- I didn't add them. I really don't like taking things out of an existing codebase except it's to improve the performance, or it's the decision of the project stakeholders. I've reached out to @dkayiwa  and @LWanjiru  about this

**Comment by dkayiwa** [comment]
@cnagadya that is a very good way of checking against our guidelines! 👍 
@joel-ace can you share with that rest of the team what we have agreed upon in regards to this?

**Pull request merged**
