### PR TITLE
CB: 31: Encounter component - Make search request

### PR DESCRIPTION
**Pull request by femioladeji**
# JIRA TICKET NAME:
Edit CB: 31: [Encounter component - Make search request](https://issues.openmrs.org/browse/CB-31)
## SUMMARY:
Make search request on the encounter tab to retrieve patients that have had encounters at different locations over a period.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@andela-foladeji can you take a look at the travis failure?

**Comment by femioladeji** [comment]
The failure is as a result of some poorly written tests, we've created a new task to address that issue in the new sprint. It will be the next PR to be raised.

**Comment by dkayiwa** [comment]
@andela-foladeji so is this now ready for merging?

**Comment by femioladeji** [comment]
Give me a second to pull the new updates so that the travis build will pass @dkayiwa

**Comment by femioladeji** [comment]
@dkayiwa yes it can be merged now

**Pull request merged**
