### PR TITLE
CB-2: Add standardEmrPage header to the index.html

### PR DESCRIPTION
**Pull request by fortunee**
# JIRA TICKET NAME:
CB-2
## SUMMARY:
This PR adds standardEmrPage header with the User button, a dropdown of menus and a logout button.

### CODE REVIEW

**Comment by fortunee** [comment]
Hi @dkayiwa When I squash and push, I get conflicts that need to be resolved and committed which ends up making it a total of 2 commits. I've tried it a few times now and I can't seem to get one single commit of every squashed commit. According to @djazayeri in his comment on the previous PR, I think you can squash during your merge. What do you say?

**Comment by dkayiwa** [comment]
@andela-efortune which comment was that?

**Comment by fortunee** [comment]
@dkayiwa Look through the comments on this closed PR https://github.com/openmrs/openmrs-owa-cohortbuilder/pull/4

**Comment by dkayiwa** [comment]
@andela-efortune i have never used that feature and hence do not know how to do it. :)

**Comment by fortunee** [comment]
Does it really need to be one single commit before, the PR can be accepted and merged? @dkayiwa

**Comment by dkayiwa** [comment]
Easier to review when a single commit.

**Comment by fortunee** [comment]
Oh, I see. now, what do we do about this? @dkayiwa

**Comment by dkayiwa** [comment]
Have you looked at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by fortunee** [comment]
Yes, I have and I see the thing with squashing? 
Well, let me take my time and go through it again. @dkayiwa

**Comment by dkayiwa** [comment]
Yes check the comments sections for hints from Steven and Lluis regarding how to squash.

**Pull request closed without merging**
