### PR TITLE
CB-22: Get Patient Attributes data from the Reporting Rest Module

### PR DESCRIPTION
**Pull request by emekanwankwo**
# JIRA TICKET NAME:
CB-22: Get Patient Attributes data from the Reporting Rest Module

## SUMMARY:

Fetch patient attributes field data from the backend for use in the UI.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Is this data coming from the reportingrest module?

**Comment by emekanwankwo** [comment]
Yes @dkayiwa, it's being fetched from the `/personattributetype` endpoint.

**Comment by dkayiwa** [comment]
How does the complete url look like?

**Comment by emekanwankwo** [comment]
The complete URL on my local machine is `http://localhost:8080/openmrs-standalone/ws/rest/v1/personattributetype`, I did not have to include the base URL (`http://localhost:8080/openmrs-standalone/ws/rest/v1`) in this PR because it has already been handled in the `apiHelper.js` file in the PR merged earlier from Femi and the `fetchData` method passed to the patientComponent as `props`. So I just had to make a call to the `fetchData` method specifying the endpoint where data is needed from, which in this case is `/personattributetype`.

**Comment by dkayiwa** [comment]
OK. Then that comes from the webservicesrest instead of reportingrest module.
For reportingrest, the url would be: http://localhost:8080/openmrs-standalone/ws/rest/v1/reportingrest/personattributetype

**Comment by emekanwankwo** [comment]
Ok, I see, let me quickly take a look at that.

**Comment by dkayiwa** [comment]
You do not have to because you will not find it in reportingrest. :)
I just wanted to communicate that it is in the webservices rest module. https://wiki.openmrs.org/display/docs/REST+Module

**Comment by emekanwankwo** [comment]
Yes, I just noticed that now. Thanks Daniel.

**Pull request merged**
