### PR TITLE
CB-119: restructure the way patient component UI elements are organized

### PR DESCRIPTION
**Pull request by kingisaac95**
# JIRA TICKET NAME:
CB-119 - [Restructure UI for patient component tab](https://issues.openmrs.org/browse/CB-119)
## SUMMARY:
Redesign the layout of components and form elements in the tab while maintaining the OpenMRS theme.

### Below are images of before and after the restructuring

before

after

### CODE REVIEW

**Comment by dkayiwa** [comment]
@kingisaac95 did you notice the merge conflicts here?

**Comment by kingisaac95** [comment]
@dkayiwa It's due to the recently merged PRs. I'll rebase, fix them and update this PR

**Comment by kingisaac95** [comment]
@dkayiwa I have fixed the merge conflict

**Comment by dkayiwa** [comment]
i have taken a closer look at the changes but i do not see how this is better than the old. May be you could create a talk post with the two screenshots to let others vote or comment.

**Comment by kingisaac95** [comment]
@dkayiwa I've updated the description above including the images. I guess that might have been the reason why you didn't see any changes. Please review the images and revert.

**Comment by dkayiwa** [comment]
@kingisaac95 i saw the changes but still find the original looking better than your changes. Besides, they even both still cover the same screen space.

**Comment by dkayiwa** [comment]
If you are not convinced, you can post it on talk for feedback from the community.

**Comment by kingisaac95** [comment]
Okay, I'll do that @dkayiwa

**Comment by dkayiwa** [comment]
Closing this because of the discussion that is going on here. https://talk.openmrs.org/t/ui-restructuring-for-cohort-builder-patient-component/12821

**Pull request closed without merging**
