### PR TITLE
CB-196 - modified the clear search results confirmation message

### PR DESCRIPTION
**Pull request by ridmal**
[CB-196](https://issues.openmrs.org/projects/CB/issues/CB-196?filter=allopenissues) - Clear search results confirmation message 

## SUMMARY:
modified the clear search results confirmation message using react-confirm-alert component.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you squash these commits into one as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by ridmal** [comment]
ok i will

**Comment by ridmal** [comment]
Is this the way to do what you mentioned @dkayiwa ?

**Comment by dkayiwa** [comment]
Can you also include a link to the ticket, as mentioned on the pull request tips page?

**Comment by ridmal** [comment]
yes, I included the link to the ticket.

**Comment by dkayiwa** [comment]
Can you also squash the commits into one as mentioned on the pull request tips page?

**Comment by ridmal** [comment]
As it said I will send a new PR form a new branch with the name of the ticket. Is it ok?

**Comment by ridmal** [comment]
@dkayiwa can you please close this PR and review my new PR  for this issue. 
https://github.com/openmrs/openmrs-owa-cohortbuilder/pull/179

**Pull request closed without merging**
