### PR TITLE
CB-2: Add standardEmrPage header to the index.html 

### PR DESCRIPTION
**Pull request by fortunee**
This PR adds standardEmrPage header with the User button, a dropdown of menus and a logout button.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@andela-efortune did you notice the merge conflicts on this pull request?
You will need to pull in order to get Daniel's changes which were merged.

**Comment by fortunee** [comment]
@dkayiwa fixed 😁

**Comment by dkayiwa** [comment]
Can you squash the commits into one as recommended at https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by djazayeri** [comment]
By the way I gave recently noticed that github has an option for the merger
to "squash and merge" with one click. (I don't know if that need to the
submitter's branch though.)

-Darius (by phone)

**Pull request closed without merging**
