### PR TITLE
[Fix]search works for unauthenticated user

### PR DESCRIPTION
**Pull request by paulupendo**
# JIRA TICKET NAME: CB-85
[Click here to view ticket on JIRA](https://issues.openmrs.org/browse/CB-85?filter=17752)
## SUMMARY:
Prevents concept search from working for an unauthenticated user.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@paulupendo could you be knowing why typing "bloo" very fast does not return any results? Or isn't the same behavior that you see?

**Comment by paulupendo** [comment]
@dkayiwa I think its is something to do with the time it takes to make the api call and get a response. If there was a way to optimize it my guess would be that typing 'bloo' too fast or slow would all work perfectly.

**Comment by dkayiwa** [comment]
@paulupendo i have tested these changes by typing concepts after i have logged out from another tab, and and not redirected to the login window when i type. Was that your intention?

**Comment by paulupendo** [comment]
@dkayiwa work perfectly from my end. Care to jump on a quick call so I replicate the bug and show you show the fix works.

**Comment by dkayiwa** [comment]
@paulupendo if you used another tab to logout, does just typing concepts in the existing tab automatically take you to the login screen? If yes, are these changes on modules-refapp?

**Comment by paulupendo** [comment]
@dkayiwa When you logout from the first tab then try make aa search on the new tab it redirects you to the login page. Not yet. But I can have them on the modules-refapp.

**Comment by paulupendo** [comment]
@dkayiwa I have just uploaded the changes to the modules-refapp and it works fine.

**Comment by paulupendo** [comment]
@dkayiwa Do you advice for me to close this PR as the bug seems to come from the platform application?

**Comment by dkayiwa** [comment]
Yes just close it.

**Pull request closed without merging**
